plone/plone.app.z3cform

- CHANGES.rst
- plone/app/z3cform/configure.zcml
Use the more specific browser layer IPloneFormLayer for adapter registrations. This avoids double registration errors.
obsoletes: #17
> use more specific form layer

- plone/app/z3cform/tests/test_objectsubform.py
- plone/app/z3cform/tests/test_widgets.py
- plone/app/z3cform/tests/tests.py
- setup.py
Since python 2.7 unittest2 was already merged with unittest.
> No need for unittest2

- CHANGES.rst
- plone/app/z3cform/tests/test_widgets.py
- plone/app/z3cform/widget.py
that way, options can be customized by adapting the FieldWidget and set the pattern_options on it, as it can be done for other widgets too.
> Allow time options to be customized for DatetimeWidget.

- CHANGES.rst
- plone/app/z3cform/widget.py
When the form context where the field is used does not have an acquisition chain to the root of the site, there is an attribute error with getToolByName. This affects products like collective.cover.
The text widget in plone.app.textfield did this context wrapping to avoid this type of issue, so I used the same strategy here.
> wrap context to allow tools to be found in text widget

- CHANGES.rst
- plone/app/z3cform/widget.py
roles_allowed_to_add_keywords wasn't used at all for Dexterity.
> fix: Check if user can add keywords for AjaxSelectWidget

- CHANGES.rst
- plone/app/z3cform/tests/test_widgets.py
- plone/app/z3cform/widget.py
Otherwise the widget lets you enter new terms, which will then fail validation.
> in AjaxSelectWidget, allowNewItems should be false for Choice fields

- plone/app/z3cform/templates/macros.pt
It's currently not possible to insert any html by overriding the template on a form and using a fill-slot to insert something between the fields and the action buttons in a form. There's formtop and formbottom, but no belowfields. 
Example use case: we want to provide an extra snipped on a controlpanel form from plone.app.registry.browser.controlpanel, which generates everything for us, but it is almost impossible to add an extra text without resorting to inserting custom fields/etc.
Suggestions for a better name than 'belowfields' are appreciated.
> Add metal slot for inserting stuff below fields

- CHANGES.rst
- plone/app/z3cform/tests/test_widgets.py
- plone/app/z3cform/widget.py
Fix related items widget tests to include root path support. Fix options merging for TinyMCE widget.
Ensure vocabulary lookup works on non-EditForms.
Allow overriding widget pattern_options dynamically using ComputedWidgetAttribute.
> Fixes related to RelatedItems Navigation Root Support

- CHANGES.rst
- plone/app/z3cform/tests/test_widgets.py
Fix a test for https://github.com/plone/plone.app.widgets/pull/132 and use assertDictEqual (dict are not ordered and assertEqual compare them as string).
> fix: relateditems test for plone.app.widgets

- CHANGES.rst
- plone/app/z3cform/tests/test_widgets.py
- plone/app/z3cform/widget.py
- Set the ``firstDay`` option on the ``DatetimeWidget`` likewise as ``DateWidget``.
- Don't overwrite widget default css classes when rendering pattern widgets.
This allows setting a css class via the ``klass`` keyword in plone.autoform widget directives.
> Allow to set CSS class via plone.autoform directives

- CHANGES.rst
- plone/app/z3cform/tests/test_utils.py
- plone/app/z3cform/tests/test_widgets.py
- plone/app/z3cform/utils.py
- plone/app/z3cform/widget.py
Support functions as values in the ``pattern_options`` dictionary, whch gets then serialized to JSON.
Before that, walk recursively through ``pattern_options`` and call all functions with the widgets context.
This allows for context-specific, runtime evaluated pattern option values.
> Call callables in pattern options

- CHANGES.rst
- plone/app/z3cform/widget.py
This avoids breaking on some z3c.form versions.
See https://github.com/zopefoundation/z3c.form/issues/44
> In select widget, accept items as property or method.

- CHANGES.rst
- plone/app/z3cform/widget.py
This avoids breaking on some z3c.form versions.
> In select widget, accept items as property or method. [1.x]

- CHANGES.rst
- plone/app/z3cform/tests/test_widgets.py
- setup.py
While this is not a breaking change functionality or API wise, the tests do only pass with plone.app.widgets 2.1.
> Test fixes for plone.app.widgets 2.1.

- CHANGES.rst
- plone/app/z3cform/converters.py
Fix RelatedItemsDataConverter with relation lists, where in an iteration a wrong value was checked to be existent.
Fixes failures in situations, where a ``None`` value was part of the relation list.
Looks like, the problem was introduced when the converter code was copied over from plone.app.widgets. p.a.w 1.x branch does it right:
https://github.com/plone/plone.app.widgets/blob/1.x/plone/app/widgets/dx.py#L335
Note the PR for 1.x branch: https://github.com/plone/plone.app.z3cform/pull/56
> RelatedItemsDataConverter fix

- CHANGES.rst
- plone/app/z3cform/converters.py
- plone/app/z3cform/tests/test_widgets.py
because of choice value type being None
For example, the following widget works only after this change.
```
<field type="zope.schema.List" name="paths"
form:widget="plone.app.z3cform.widget.RelatedItemsFieldWidget">
<title i18n:ranslate="">Searchable folders</title>
<required>False</required>
<value_type type="zope.schema.Choice">
<source>path.to.instance.of.plone.app.vocabularies.catalog.CatalogSource</source>
</value_type>
</field>
```
> Fix issue where RelatedItemsDataConverter failed to convert list of choices

- CHANGES.rst
- plone/app/z3cform/tests/test_widgets.py
- plone/app/z3cform/widget.py
- Do not show the Clear button for required Date or DateTime fields.
- Test fixes for plone.app.widgets 2.1.
> pickadate optimizations

- CHANGES.rst
- plone/app/z3cform/inline_validation.rst
- plone/app/z3cform/templates.py
- plone/app/z3cform/templates/macros.pt
- plone/app/z3cform/tests/example.py
- plone/app/z3cform/tests/test_objectsubform.py
- plone/app/z3cform/tests/test_utils.py
- plone/app/z3cform/tests/test_widget.py
- plone/app/z3cform/tests/test_widgets.py
- setup.py
Add new class ``form-view-name-VIEWNAME`` to form element indicating the view name w/o old kss prefix. New class's replaces ``++`` in view by ``__`` in order to produce valid class (CSS selectable) names. Old class is still in place for bbb reasons, even if it has limited value.
> Add new class form-view-name-VIEWNAME to form element

- CHANGES.rst
- plone/app/z3cform/configure.zcml
- plone/app/z3cform/converters.py
- plone/app/z3cform/interfaces.py
- plone/app/z3cform/templates/link_input.pt
- plone/app/z3cform/tests/test_widgets.py
- plone/app/z3cform/utils.py
- plone/app/z3cform/widget.py
Moved the "better link widget" from this PR to here:
https://github.com/plone/plone.app.contenttypes/pull/367
Note: As opposed to the other widgets in plone.app.z3cform, this one isn't plone.app.widgets based - although it uses the related items widget from mockup. 
Note: As this is not a plone.app.widgets based widget, there are no ``pattern_options`` to be configured via the plone.autoform widget directive...
> A better link widget

- CHANGES.rst
- plone/app/z3cform/configure.zcml
- plone/app/z3cform/converters.py
- plone/app/z3cform/interfaces.py
- plone/app/z3cform/templates.py
- plone/app/z3cform/templates/singlecheckbox.pt
- plone/app/z3cform/templates/singlecheckboxbool_display.pt
- plone/app/z3cform/templates/singlecheckboxbool_hidden.pt
- plone/app/z3cform/templates/singlecheckboxbool_input.pt
- plone/app/z3cform/templates/widget.pt
- plone/app/z3cform/widget.py
- setup.py
replaced existing hack by a real widget.
> fixes #64: SingleCheckBoxFieldWidget does not render value in view mode

- CHANGES.rst
- plone/app/z3cform/converters.py
- plone/app/z3cform/templates/link_input.pt
- plone/app/z3cform/tests/test_widgets.py
Fix in link widget data converter for ``toWidgetValue`` to return an empty structure when the field value is empty instead of returning the portal root object.
Fixes: https://github.com/plone/Products.CMFPlone/issues/2163
Also: add placeholders for email and external link.
Merge together:
https://github.com/plone/plone.app.contenttypes/pull/431
https://github.com/plone/plone.app.z3cform/pull/76
> Link widget data converter: return empty on empty input

- CHANGES.rst
- plone/app/z3cform/converters.py
With the new linkwidget links are stored as a dictionary. Old text links are converted to the new structure. The converter tries to traveres the link and convert to an internal link if it succeeds. If the link has a query string this is lost. This PR fixes that.
> - Keep internal links with query strings as external

- CHANGES.rst
- plone/app/z3cform/templates/singlecheckboxbool_input.pt
The description could be an HTML snippet, so *structure* is needed as appeared in the deprecated 
singlecheckbox.pt
> Fix SingleCheckBoxBoolWidget description to render structure

- CHANGES.rst
- plone/app/z3cform/widget.py
This fixes rendering errors when instantiating the pattern under
Python3 as lxml expects unicode or ASCII.
> Change the RichTextWidget to use unicode

- CHANGES.rst
- plone/app/z3cform/templates/macros.pt
Screen readers could now see and read correctly alerts/status messages.
> a11y: added role attribute for portalMessage

- CHANGES.rst
- plone/app/z3cform/configure.zcml
- plone/app/z3cform/converters.py
- plone/app/z3cform/factories.py
- plone/app/z3cform/interfaces.py
- plone/app/z3cform/templates/ajaxselect_display.pt
- plone/app/z3cform/tests/test_widgets.py
- plone/app/z3cform/widget.py
- setup.py
all started in see https://github.com/plone/plone.app.vocabularies/pull/56#issuecomment-476598570
Fixes AjaxSelectWidget to respect tokens different from values in vocabularies.
This includes changes in both, the converter and the widget itself. 
A test was added too.
``get_ajaxselect_options`` from ``plone.app.widgets.utils`` is assimilated by the widget now too simplify the whole code,  so the one in the other package is dead code now and will be deprecated there.
> Fix value conversion in AjaxSelectWidget to respect tokens

- news/107.bugfix
- plone/app/z3cform/templates/macros.pt
if `view/method`  raises attributeerror the html form has a wrong method attribute
`<form method="'post'&#10;                                      " ...`
> Fix wrong default for method attribute in pt

- news/111.feature
- plone/app/z3cform/configure.zcml
- plone/app/z3cform/templates/relateditems_display.pt
- plone/app/z3cform/widget.py
Display items from RelationChoice and RelationList fields instead of showing only uuids.
As discussed in https://community.plone.org/t/widget-view-shows-uid-value/4352/5
Display with this change:
Display before:
> Add template to display related items

- news/152.bugfix
- plone/app/z3cform/widget.py
This was [fixed in Python 3.2](https://bugs.python.org/issue1777412).
Now the lowest date here is year 1, this restriction comes from Python `datetime` package itself.
> Remove the before 1900 dates formatting hack.

- news/151.bugfix
- news/151.feature
- plone/app/z3cform/configure.zcml
- plone/app/z3cform/converters.py
- plone/app/z3cform/widget.py
In past one could use the `zope.schema.datetime` field with a `DatetimeWidget` and set a pattern-option `"time": False` to  switch off selecting a time in the form. This got you a full datetime stored (with timezone!), and there are use cases where this is needed.
Now, with native browser widget this is not possible anymore and the feature is broken (regression).
To get the feature back, I register here a new converter which kicks in if a `DateFieldWidet` is used on a `zope.schema.datetime` with the same behavior: setting the time to "00:00". 
This implies one need to touch all schemas when migrating from 5.2 to 6.0b1.
> add converter to use a date widget on a datetime field

- news/87.bugfix
- plone/app/z3cform/templates/macros.pt
Fixes https://github.com/plone/plone.app.z3cform/issues/87
> Allow non-default fieldset labels to be translated

- news/167.bugfix
- plone/app/z3cform/tests/test_utils.py
- plone/app/z3cform/tests/test_widgets.py
- plone/app/z3cform/utils.py
- plone/app/z3cform/widgets/patterns.py
There are several issues and questions on community.plone.org reporting this traceback and we've been hit by this today in latest Plone `6.0.4` with customer pasted text.
```
...
File "/home/workspace/src/plone.app.z3cform/plone/app/z3cform/tests/test_widgets.py", line 1716, in test_unicode_control_characters_value
widget.render(),
File "/home/workspace/src/plone.app.z3cform/plone/app/z3cform/widgets/richtext.py", line 104, in render
return renderer(self)
File "/home/workspace/src/plone.app.z3cform/plone/app/z3cform/widgets/richtext.py", line 178, in tinymce_richtextwidget_render
return RichTextWidget.render_input_mode(widget)
File "/home/workspace/src/plone.app.z3cform/plone/app/z3cform/widgets/richtext.py", line 129, in render_input_mode
textarea_widget = self._base(None, None, …
```
> Remove invalid "unicode control characters" for `TextareaWidget` value

- news/173.feature
- plone/app/z3cform/interfaces.py
- plone/app/z3cform/templates/email_input.pt
- plone/app/z3cform/widgets.zcml
- plone/app/z3cform/widgets/email.py
- setup.py
Currently email input from `plone.schema.email` is not validated on the client because it does not use the email field type. In past it was sometimes a problem using this field, since browsers did not support this field types well enough. Meanwhile this is not a problem any more.
> Use html 5 email field for plone.schema email fields

- news/179.bugfix
- plone/app/z3cform/templates/macros.pt
fixes #179 
see also https://github.com/plone/plone.schemaeditor/issues/106
> Ignore form validation if `ignoreRequiredOnExtract` is set

- news/158.feature
- plone/app/z3cform/templates/macros.pt
> Add `row` container to enable column layout for fields using `wrapper_css_class`

- news/193.bugfix
- plone/app/z3cform/interfaces.py
- plone/app/z3cform/widgets.zcml
- plone/app/z3cform/widgets/password.py
Plone 6.1 login has currently an `input[type=text]` as password field. This fixes it.
> Implement missing PasswordWigdet adapter

- news/198.feature
- plone/app/z3cform/templates/file_input.pt
- plone/app/z3cform/templates/image_input.pt
- setup.py
If the widget's field - if there is one - has  set (the  field has  set by default) the allowed content types are rendered as  attribute on the file input.
This already restricts the allowed file types before uploading while still being checked on the server side too.
Fixes: https://github.com/plone/plone.formwidget.namedfile/issues/66 Depeds on:
- https://github.com/plone/plone.namedfile/pull/158
- https://github.com/plone/plone.formwidget.namedfile/pull/67
> Add support for accept attribute on file input (4.3.x branch)

- .editorconfig
- .flake8
- .github/workflows/meta.yml
- .gitignore
- .meta.toml
- .pre-commit-config.yaml
- dependabot.yml
- news/198.feature
- plone/app/z3cform/templates/file_input.pt
- plone/app/z3cform/templates/image_input.pt
- pyproject.toml
- setup.py
- tox.ini
If the widget's field - if there is one - has  set (the  field has  set by default) the allowed content types are rendered as  attribute on the file input.
This already restricts the allowed file types before uploading while still being checked on the server side too.
Fixes: https://github.com/plone/plone.formwidget.namedfile/issues/66 Depeds on:
- https://github.com/plone/plone.namedfile/pull/158
- https://github.com/plone/plone.formwidget.namedfile/pull/67
> Add support for accept attribute on file input.

- news/#201.feature
- plone/app/z3cform/templates/checkbox_input.pt
- plone/app/z3cform/templates/radio_input.pt
- plone/app/z3cform/templates/widget.pt
Can be used like this, to realize Bootstrap Checkbox/Radio Toggle Buttons.
```
directives.widget(
"graduation",
CheckBoxFieldWidget,
klass="btn-check",
label_css_class="btn btn-outline-primary",
)
graduation = schema.List(
required=False,
title=_("Graduation"),
value_type=schema.Choice(
vocabulary="example.AvailableGraduationGroups",
),
)
```
> use label_css_class attribute from widget if available in checkbox_input & radio_input [4.3.x]

- news/#202.feature
- plone/app/z3cform/templates/checkbox_input.pt
- plone/app/z3cform/templates/radio_input.pt
- plone/app/z3cform/templates/widget.pt
- setup.py
Can be used like this, to realize Bootstrap Checkbox/Radio Toggle Buttons.
```
directives.widget(
"graduation",
CheckBoxFieldWidget,
klass="btn-check",
label_css_class="btn btn-outline-primary",
)
graduation = schema.List(
required=False,
title=_("Graduation"),
value_type=schema.Choice(
vocabulary="example.AvailableGraduationGroups",
),
)
```
> use label_css_class attribute from widget if available in checkbox_input & radio_input [master]

- news/197.feature
- plone/app/z3cform/converters.py
- plone/app/z3cform/converters.zcml
- plone/app/z3cform/interfaces.py
- plone/app/z3cform/templates/contentbrowser_display.pt
- plone/app/z3cform/templates/link_input.pt
- plone/app/z3cform/tests/test_widgets.py
- plone/app/z3cform/widgets.zcml
- plone/app/z3cform/widgets/contentbrowser.py
`ContentBrowserWidget` is simply a copy of `RelatedItemsWidget` and exposes the new `pat-contentbrowser` which has the same API and features as `pat-relateditems` right now. 
The following core modules use `RelatedItemsFieldWidget`:
- plone.app.relationfield.behavior
- plone.app.multilingual.interfaces
- plone.portlet.collection.collection
- plone.volto.behavior.preview_link
- plone.volto.coresandbox.example
~For now we only update the `relatedItems` field in plone.app.relationfield. The others can be updated afterwards.~
~UPDATE No. 1: `RelatedItemsWidget` is now a pure alias of `ContentBrowserWidget` using `zope.deferredimport`~
UPDATE No. 2: `RelatedItemsWidget` is not replaced! Everything works like before, only `ContentBrowserWidget` functionality is added. Nothing changes until …
> Implement `ContentBrowserWidget` for the new `pat-contentbrowser` pattern

- news/213.bugfix
- plone/app/z3cform/widgets/link.py
This came up on a virtualhostmonster hosted site here because `rootUrl` and `baseUrl` are be empty in that case. `ContentBrowserWidget` needs at least the physical root url of the plone site.
> Fix pattern options for `LinkWidget`

- news/230.bugfix.rst
- plone/app/z3cform/utils.py
- plone/app/z3cform/widgets/contentbrowser.py
> Allow the ContentBrowserWidget to be used inside an object widget

- news/225.bugfix
- news/235.bugfix
- plone/app/z3cform/templates/ajaxselect_display.pt
- plone/app/z3cform/templates/select_input.pt
- plone/app/z3cform/tests/test_widgets.py
- plone/app/z3cform/widgets/select.py
fixes #235 
fixes #225 
Note: the correct vocab term definition for `TreeVocabulary.fromDict` is a 3-value tuple: `(value, token, title)` otherwise you don't get the title in the selector ... see tests as example: https://github.com/plone/plone.app.z3cform/pull/236/files#diff-ae663d5ec04abc1eeb5d5f36aeb1452a80a7f7a1b59eafffe5ed9d0d6db171f2R644-R655 and also the implementation in `example.contenttype` https://github.com/collective/example.contenttype/pull/10
> Fix `TreeVocabulary` implementation and `AjaxSelectWidget` display template
