plone/plone.app.z3cform

plone/app/z3cform/queryselect/__init__.py, plone/app/z3cform/wysiwyg/widget.py
=> add deprecation warnings to wysiwyg and queryselect

plone/app/z3cform/tests/test_widgets.py
Fix a test for https://github.com/plone/Products.CMFPlone/pull/1088
=> fix a test for https://github.com/plone/Products.CMFPlone/pull/1088

plone/app/z3cform/tests/test_widgets.py
=> tests: #29 Check if user can add keywords for AjaxSelectWidget

CHANGES.rst, plone/app/z3cform/tests/test_widgets.py
Fix a test for https://github.com/plone/plone.app.widgets/pull/114
=> fix: tests for https://github.com/plone/plone.app.widgets/pull/114

CHANGES.rst, plone/app/z3cform/widget.py
=> Use output_relative_to(self.context) in RichTextWidget

CHANGES.rst, plone/app/z3cform/converters.py, plone/app/z3cform/templates.py, plone/app/z3cform/tests/layer.py, plone/app/z3cform/tests/test_utils.py, plone/app/z3cform/tests/test_widgets.py, plone/app/z3cform/tests/tests.py, plone/app/z3cform/utils.py, plone/app/z3cform/widget.py, plone/app/z3cform/wysiwyg/widget.py
Less annoying errors reported in order to focus on the important ones.
=> Cleanup code analysis errors

CHANGES.rst, plone/app/z3cform/widget.py
https://github.com/plone/Products.CMFPlone/issues/2446
=> Allow related items widget to be used in subforms 

CHANGES.rst, plone/app/z3cform/wysiwyg/widget.py
Fixes https://github.com/plone/Products.CMFPlone/issues/2605
=> Fix deprecation warning

CHANGES.rst, plone/app/z3cform/converters.py
Adding toFieldValue method to LinkWidgetDataConverter
see https://github.com/plone/plone.app.z3cform/issues/102
=> LinkFieldWidget in DataGridField shows error on correct value 

news/105.bugfix, plone/app/z3cform/converters.py
see plone/Products.CMFPlone#2885
=> fixes plone/Products.CMFPlone#2885

news/115.bugfix, plone/app/z3cform/templates/macros.pt
This fixes https://github.com/plone/Products.CMFPlone/issues/3126
=> Fix message type like Error not translated in add form

news/121.feature, plone/app/z3cform/converters.py
=> Added ValueError in Exception for vocabularyfields

news/138.bugfix, plone/app/z3cform/templates/form.pt
=> Re-enable HTML rendering in form description

news/134.bugfix, plone/app/z3cform/configure.zcml, plone/app/z3cform/converters.py, plone/app/z3cform/tests/test_widgets.py, plone/app/z3cform/widget.py
time widget now adds value and name attributes
might help fixing
https://github.com/plone/Products.CMFPlone/issues/3409
=> adding name and value to TimeWidget

news/325.bugfix, plone/app/z3cform/templates/macros.pt
See https://github.com/collective/collective.easyform/issues/325
=> Add name attribute to form, if view.form_name is defined. [master]

news/325.bugfix, plone/app/z3cform/templates/macros.pt
See https://github.com/collective/collective.easyform/issues/325
=> Add name attribute to form, if view.form_name is defined. [Plone 5.2]

plone/app/z3cform/templates/macros.pt
With recent fixes in pat-validation the issues should be gone (e.g. not being able to reset a form due to multiple submit buttons).
Revert "temporary remove pat-validation"
This reverts commit d7af3bca77063dc86d7c2cfd56f1eecd6327c9e6.
=> Re-enable form validation.

news/156.bugfix, plone/app/z3cform/templates/textarea_input.pt
=> Include `required` attribute for `<textarea>` fields.

news/160.bugfix, plone/app/z3cform/templates/link_input.pt
=> Fix relative URLs validation in link widget

news/3764.feature, plone/app/z3cform/configure.zcml, plone/app/z3cform/factories.py
To be merged together with https://github.com/plone/plone.namedfile/pull/141
=> Deprecate storage

news/170.bugfix, plone/app/z3cform/templates/orderedselect_input.pt
Fixes #168 
This is a successor of #169
=> Add `required` to orderedselect widget

news/87.bugfix, plone/app/z3cform/templates/macros.pt
Fix https://github.com/plone/plone.app.z3cform/issues/87 for Plone 5.2
Backport of https://github.com/plone/plone.app.z3cform/pull/153
=> Fieldset labels translatable

news/190.bugfix, plone/app/z3cform/tests/test_widgets.py, plone/app/z3cform/widgets/base.py
=> Add missing `pattern_options` multiadapter

news/219.bugfix, plone/app/z3cform/widgets/richtext.py
=> Fix deprecated adapter lookup

news/228.bugfix.rst, plone/app/z3cform/templates/singlecheckboxbool_hidden.pt
=> Fix the boolean widget in hidden mode
